name: Manual workflow
on: [ workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        uses: takost/write-args-action@v1.2
        with:
          args: hello 'there'
