name: Manual workflow
on: [ workflow_dispatch ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@4dafa43b526f3e34af838be95f642fb5369e34ff
    - uses: takost/write-args-action@main
      with:
        args: "hello"
    
