name: Manual workflow
on: [ workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: takost/write-args-action@main
      with:
        args: "hello"
    
