name: Manual workflow
on: [ workflow_dispatch ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    
